[package]
name = "bevy_osc"
version = "0.1.0"
authors = ["Mikkel Luja Rasmussen <mlr@redbarnet.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou_osc = "0.16.0"