[package]
name = "bevy_osc"
version = "0.1.0"
authors = ["Mikkel Rasmussen <bphlox@gmail.com>"]
edition = "2018"
license = "MIT OR ISC"
readme = "README.md"
repository = "https://github.com/BlackPhlox/bevy_osc"
documentation = "https://docs.rs/bevy_osc"
description = ""
keywords = ["gamedev", "bevy", "camera", "fps", "3d", ]
categories = ["game-development", "game-engines", "encoding" ]
exclude = [
    ".github/*",
    "credits/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#TODO: Only use required features of bevy
bevy = "0.5"
nannou_osc = "0.16.0"